### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by miha-skalic** [OpenEye-Contrib/Reflex3D#1]
Hi, 
are there any plans to make this software independent of OE? 
Given that it is dependent on the underlying software suit makes it kinda useless.

**Comment by DavidACosgrove** [comment]
I take issue with the suggestion that this is useless.  It is the protocol we used to produce the results in the paper, so that other people can reproduce our results and build on them if they want to.  In that sense, it is no different from producing the input scripts for running Glide or Desmond or some other 3rd party comp. chem. tool.  You wouldn't be asking us if we were going to re-write an FEP or Docking program in that case.  I can't see the distinction, personally.  If you think the procedure is likely to be useful to you, you can always contact OpenEye for a license, or you can re-write it from theory yourself.  We have the necessary OE licenses, so we don't need to do the latter.  Software is expensive to write, debug and support and it is not reasonable to expect it to be free, any more than you should expect your computer to be free.

**Comment by miha-skalic** [comment]
hey man, sorry for saying it is useless.
